spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 1000
  cache:
    redis:
      cache-null-values: true
rocketmq:
  name-server: localhost:9876
server:
  port: 18903