spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 1000
  cache:
    redis:
      cache-null-values: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:18848
